#ifndef GUESSTURE_H
#define GUESSTURE_H

#include <QString>
#include <opencv2/opencv.hpp>

class Guessture
{    
public:
    Guessture();
    Guessture(QString name, QString musicFile, QString imageFile, QString hint1, QString hint2, int maxTimeNoob, int maxTimeNerd);
    virtual ~Guessture();

    void start();
    void skip();
    int end();

    bool isActive();
    QString getHint();
    QString getName() const;
    QString getImageFile() const;

    int getTimeStars() const;
    int getHintStars() const;
    int getStars() const;

    virtual bool analyze(const cv::Mat& bitmap);

private:

    //basic guessture infos
    QString s_name;
    QString s_musicFile;
    QString s_imageFile;
    QString s_hint1;
    QString s_hint2;
    int i_noobTime;
    int i_nerdTime;

    //Infos generated by user-behavior
    int i_startTime;
    int i_endTime;
    int i_timeStars;
    int i_hintStars;
    bool b_usedHint1;
    bool b_usedHint2;
};

#endif // GUESSTURE_H
